# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstore.proto\x12\x05store\"\x11\n\x0fGetPriceRequest\"!\n\x10GetPriceResponse\x12\r\n\x05price\x18\x01 \x01(\x05\"\x1f\n\x0bSellRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\" \n\x0cSellResponse\x12\x10\n\x08response\x18\x01 \x01(\x05\"\x15\n\x13\x45ndExecutionRequest\"F\n\x14\x45ndExecutionResponse\x12\x16\n\x0eseller_balance\x18\x01 \x01(\x05\x12\x16\n\x0epending_orders\x18\x02 \x01(\x05\x32\xcb\x01\n\x0cStoreService\x12=\n\x08GetPrice\x12\x16.store.GetPriceRequest\x1a\x17.store.GetPriceResponse\"\x00\x12\x31\n\x04Sell\x12\x12.store.SellRequest\x1a\x13.store.SellResponse\"\x00\x12I\n\x0c\x45ndExecution\x12\x1a.store.EndExecutionRequest\x1a\x1b.store.EndExecutionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'store_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPRICEREQUEST']._serialized_start=22
  _globals['_GETPRICEREQUEST']._serialized_end=39
  _globals['_GETPRICERESPONSE']._serialized_start=41
  _globals['_GETPRICERESPONSE']._serialized_end=74
  _globals['_SELLREQUEST']._serialized_start=76
  _globals['_SELLREQUEST']._serialized_end=107
  _globals['_SELLRESPONSE']._serialized_start=109
  _globals['_SELLRESPONSE']._serialized_end=141
  _globals['_ENDEXECUTIONREQUEST']._serialized_start=143
  _globals['_ENDEXECUTIONREQUEST']._serialized_end=164
  _globals['_ENDEXECUTIONRESPONSE']._serialized_start=166
  _globals['_ENDEXECUTIONRESPONSE']._serialized_end=236
  _globals['_STORESERVICE']._serialized_start=239
  _globals['_STORESERVICE']._serialized_end=442
# @@protoc_insertion_point(module_scope)
