# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wallet.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cwallet.proto\x12\x06wallet\"&\n\x11GetBalanceRequest\x12\x11\n\towner_key\x18\x01 \x01(\t\"%\n\x12GetBalanceResponse\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x05\"4\n\x0fWithdrawRequest\x12\x11\n\towner_key\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"$\n\x10WithdrawResponse\x12\x10\n\x08response\x18\x01 \x01(\x05\"E\n\x0fTransferRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\r\n\x05\x63heck\x18\x02 \x01(\x05\x12\x11\n\towner_key\x18\x03 \x01(\t\"$\n\x10TransferResponse\x12\x10\n\x08response\x18\x01 \x01(\x05\"\x15\n\x13\x45ndExecutionRequest\".\n\x14\x45ndExecutionResponse\x12\x16\n\x0epending_orders\x18\x02 \x01(\x05\x32\xa5\x02\n\rWalletService\x12\x45\n\nGetBalance\x12\x19.wallet.GetBalanceRequest\x1a\x1a.wallet.GetBalanceResponse\"\x00\x12?\n\x08Withdraw\x12\x17.wallet.WithdrawRequest\x1a\x18.wallet.WithdrawResponse\"\x00\x12?\n\x08Transfer\x12\x17.wallet.TransferRequest\x1a\x18.wallet.TransferResponse\"\x00\x12K\n\x0c\x45ndExecution\x12\x1b.wallet.EndExecutionRequest\x1a\x1c.wallet.EndExecutionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wallet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETBALANCEREQUEST']._serialized_start=24
  _globals['_GETBALANCEREQUEST']._serialized_end=62
  _globals['_GETBALANCERESPONSE']._serialized_start=64
  _globals['_GETBALANCERESPONSE']._serialized_end=101
  _globals['_WITHDRAWREQUEST']._serialized_start=103
  _globals['_WITHDRAWREQUEST']._serialized_end=155
  _globals['_WITHDRAWRESPONSE']._serialized_start=157
  _globals['_WITHDRAWRESPONSE']._serialized_end=193
  _globals['_TRANSFERREQUEST']._serialized_start=195
  _globals['_TRANSFERREQUEST']._serialized_end=264
  _globals['_TRANSFERRESPONSE']._serialized_start=266
  _globals['_TRANSFERRESPONSE']._serialized_end=302
  _globals['_ENDEXECUTIONREQUEST']._serialized_start=304
  _globals['_ENDEXECUTIONREQUEST']._serialized_end=325
  _globals['_ENDEXECUTIONRESPONSE']._serialized_start=327
  _globals['_ENDEXECUTIONRESPONSE']._serialized_end=373
  _globals['_WALLETSERVICE']._serialized_start=376
  _globals['_WALLETSERVICE']._serialized_end=669
# @@protoc_insertion_point(module_scope)
